name: Android CI
on:
  push:
    paths:
      - ".github/workflows/android.yml"
      - "XClipper.Android/**"
  pull_request:
    paths:
      - ".github/workflows/android.yml"
      - "XClipper.Android/**"

jobs:
  android:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Building project
        run: |
          tar -xvzf scripts/gradle.tar.gz
          md XClipper.Android/.gradle
          echo keyAlias=github >> XClipper.Android/.gradle/gradle.properties
          echo keyPassword=github >> XClipper.Android/.gradle/gradle.properties
          echo storePassword=github >> XClipper.Android/.gradle/gradle.properties
          echo SERVER_URI= >> XClipper.Android/.gradle/gradle.properties
          cd XClipper.Android
          chmod +x gradlew
          ./gradlew app:assembleDebug --stacktrace
          ./gradlew app:test

  # Common action to notify on discord

  discord_notify:
    needs: [android]
    runs-on: ubuntu-latest
    steps:
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(echo ${{ github.sha }} | cut -c -7)"
      - name: Sending commit notification
        if: (!startsWith(github.event.pusher, '')) && startsWith(github.event.pusher.name, 'KaustubhPatange')
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_ANDROID }}
        uses: Ilshidur/action-discord@master
        with:
          args: Commit [${{ steps.vars.outputs.sha_short }}](${{github.event.repository.html_url}}/commit/${{ github.sha }}) had a successful build!

      - name: Sending PR notification
        if: (!startsWith(github.event.pull_request, ''))
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_PC }}
        uses: Ilshidur/action-discord@master
        with:
          args: "A new pull request is made by ${{ github.event.pull_request.user.login }}. Review it [here](${{ github.event.pull_request.html_url }})!"
