name: Build Android
on: [push, pull_request]

jobs:
  android:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Building project
        run: |
          tar -xvzf scripts/gradle.tar.gz
          cd XClipper.Android
          chmod +x gradlew
          ./gradlew app:assembleDebug --stacktrace