name: Build Windows
on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up nuget
        uses: warrenbuckley/Setup-Nuget@v1
      - name: Setting up msbuild
        uses: warrenbuckley/Setup-MSBuild@v1
      - name: Restoring dependencies & building project
        run: |
          tar -xvzf scripts\csproj.tar.gz
          nuget restore XClipper.sln
          msbuild XClipper.sln /t:Rebuild /p:WarningLevel=0 /p:Configuration=Release