name: Android CI
on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up nuget
        uses: warrenbuckley/Setup-Nuget@v1
      - name: Setting up msbuild
        uses: warrenbuckley/Setup-MSBuild@v1
      - name: Restoring dependencies & building project
        run: |
          tar -xvzf scripts\csproj.tar.gz
          nuget restore XClipper.sln
          msbuild XClipper.sln /t:Rebuild /p:WarningLevel=0 /p:Configuration=Release
  android:
    needs: [windows]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Building project
        run: |
          tar -xvzf scripts/gradle.tar.gz
          cd XClipper.Android
          chmod +x gradlew
          ./gradlew app:assembleDebug --stacktrace

  # Common action to notify on discord

  discord_notify:
    needs: [android]
    runs-on: ubuntu-latest
    steps:
      - name: Sending commit notification
        if: (!startsWith(github.event.pusher, '')) && (!startsWith(github.event.pusher.name, 'KaustubhPatange'))
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_PC }}
        uses: Ilshidur/action-discord@master
        with:
          args: "A new pull request is made by ${{ github.event.pull_request.user.login }} at ${{ github.event.pull_request.html_url }}"

      - name: Sending PR notification
        if: (!startsWith(github.event.pull_request, ''))
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_PC }}
        uses: Ilshidur/action-discord@master
        with:
          args: "A new pull request is made by ${{ github.event.pull_request.user.login }} at ${{ github.event.pull_request.html_url }}"
